#!/bin/bash
echo "Starting Testing"

X=1

while [ $X -le 1 ]
do
  echo "Test #${X}"
  r=$((RANDOM%100+1))
  c=$((RANDOM%100+1))
  echo "r=${r} c=${c}"
  ./matrix_vector_gen.py $r $c
  Y=1
  while [ $Y -le 2 ]
  do
    echo "Executing with ${Y} Procs"
    mpiexec -n $Y ./prob1.out 
    Y=$[$Y+1]
  done
  X=$[$X*10]
done
echo "Finished testing"
