#!/bin/bash
echo "Starting Testing"

X=1

while [ $X -le 10000000 ]
do
  echo "Running with ${X} elements"
  ./rand_gen.py $X > input.txt
  sed -n 2p input.txt  | tr " " "\n"  | sort -n | tr "\n" " " > unix.txt
  Y=1
  while [ $Y -le 64 ]
  do
    echo "Executing with ${Y} Procs"
    mpiexec -n $Y ./prob2.out 
    diff unix.txt output.txt
    rm output.txt
    Y=$[$Y*2]
  done
  X=$[$X*10]
done
echo "Finished testing"
